# Generated by Django 2.0.3 on 2018-05-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_code', models.CharField(max_length=34, verbose_name='仪器编码')),
                ('equip_name', models.CharField(max_length=20, verbose_name='仪器名称')),
                ('make_factory', models.CharField(max_length=30, verbose_name='制造厂家')),
                ('instrumentNum', models.IntegerField(default=0, verbose_name='设备个数')),
                ('element_num', models.IntegerField(default=0, verbose_name='要素个数')),
                ('inspectionDate', models.DateTimeField(verbose_name='到检日期')),
                ('mobile', models.CharField(choices=[('CMCC', '移动'), ('CU', '联通')], max_length=11, verbose_name='服务公司')),
            ],
            options={
                'verbose_name_plural': '仪器列表',
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='故障起始')),
                ('finish_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.FloatField(verbose_name='持续时间')),
            ],
            options={
                'verbose_name_plural': '故障列表',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_code', models.CharField(max_length=34, verbose_name='设备编码')),
                ('instrument_name', models.CharField(max_length=30, verbose_name='设备名称')),
                ('make_factory', models.CharField(max_length=30, verbose_name='生产厂家')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWSMonitor.Equipment', verbose_name='所属仪器')),
            ],
            options={
                'verbose_name_plural': '设备列表',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=100, verbose_name='类型')),
                ('stationNum', models.CharField(default='57073', max_length=5, verbose_name='区站号')),
                ('cityCode', models.CharField(default='57073', max_length=5, verbose_name='所属地区')),
                ('description', models.CharField(default='57073', max_length=5, verbose_name='说明')),
                ('stationclass', models.CharField(max_length=1)),
                ('isMask', models.CharField(max_length=1)),
                ('gprsID', models.CharField(max_length=11)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('stationName', models.CharField(max_length=10)),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('longitudebak', models.CharField(default='', max_length=15, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('latitudebak', models.CharField(default='', max_length=15, null=True, verbose_name='纬度')),
                ('high', models.FloatField(verbose_name='海拔高度')),
                ('builtdate', models.DateTimeField(verbose_name='创建时间')),
                ('lastUpdate', models.DateTimeField(verbose_name='修改时间')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('mobileNum', models.CharField(max_length=11, verbose_name='手机号')),
                ('photoFile4', models.CharField(max_length=11, verbose_name='照片')),
                ('photoFile3', models.CharField(max_length=11, verbose_name='照片')),
                ('photoFile2', models.CharField(max_length=11, verbose_name='照片')),
                ('photoFile', models.CharField(max_length=11, verbose_name='照片')),
                ('photoFile1', models.CharField(max_length=11, verbose_name='照片')),
                ('county', models.CharField(max_length=11, verbose_name='县')),
            ],
            options={
                'verbose_name_plural': '站点信息列表',
            },
        ),
        migrations.AddField(
            model_name='fault',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWSMonitor.Station', verbose_name='站名'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWSMonitor.Station'),
        ),
    ]
