# Generated by Django 2.0.3 on 2018-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSMonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='inspectionDate',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mobile',
            field=models.CharField(choices=[('CMCC', '移动'), ('CU', '联通')], default='CMCC', max_length=11, verbose_name='服务公司'),
        ),
    ]
