# Generated by Django 2.0.3 on 2018-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSMonitor', '0003_auto_20180523_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='finish_time',
        ),
        migrations.AddField(
            model_name='fault',
            name='IsRecovered',
            field=models.BooleanField(default=False, verbose_name='已恢复'),
        ),
    ]
