# Generated by Django 2.0.3 on 2018-06-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AWSMonitor', '0004_auto_20180605_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_delay_time', models.DateTimeField(verbose_name='时间')),
                ('mis_delay', models.CharField(choices=[('M', 'Missing'), ('D', 'Delay')], default='M', max_length=1, verbose_name='缺报/逾限')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWSMonitor.Station', verbose_name='站名')),
            ],
        ),
    ]
